# NumPy's arange() function

## Video 1: How to use np.arange() Overview

In [1]:
import numpy as np

np.arange

<function numpy.arange>

In [2]:
np.arange(start=1, stop=10, step=1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(10) # default start is 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1.0, 10, 1)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [9]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Video 2: Data Types

If no data type is given numpy will guess which data type to use

In [10]:
import numpy as np

x = np.arange(10)

In [13]:
x.dtype # will be an integer as there is no reason to assume floats

dtype('int32')

In [14]:
x.itemsize # in bytes

4

In [15]:
np.arange(1, 10, dtype=np.int8)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [16]:
# if changing the data type, beware of using a dtype that is too small
np.arange(1000, 1010, dtype=np.int8)

C:\Users\cfornshell\AppData\Local\Temp\ipykernel_1240\986623931.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.arange(1000, 1010, dtype=np.int8)
C:\Users\cfornshell\AppData\Local\Temp\ipykernel_1240\986623931.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1001 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.arange(1000, 1010, dtype=np.int8)


array([-24, -23, -22, -21, -20, -19, -18, -17, -16, -15], dtype=int8)

## Video 3: Manipulation

arange returns an ndarray which has useful manipulation features

In [19]:
import numpy as np

x = np.arange(5)

In [21]:
type(x)

numpy.ndarray

In [22]:
x**2

array([ 0,  1,  4,  9, 16])

In [23]:
x=np.arange(-10, 10, .5)

In [24]:
np.abs(x)

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [31]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [30]:
# you can also reshape the ndarray that gets returned
x = np.arange(1, 10)

In [28]:
x.shape

(9,)

In [29]:
x.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Video 4: arange() vs range()

Differences:
1. range only works with integers
2. range doesn't return a list/array. Numbers are generated on demand
3. np.arange is faster at creating sequences
4. meshgrid: 

In [34]:
import numpy as np

#returns an ndarrary
np.arange

<function numpy.arange>

In [35]:
#range itself is a type
type(range(10))

range

## Video 5: Other functions

There are other functions that return or produce similar outputs:
1. linspace: allows you to specify the number of elements that you want. 
2. logspace: same as linspace except it takes the log
3. gemospace: uses the geom
4

In [3]:
import numpy as np

np.arange(1, 100, 1, dtype=np.int32)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
#Notice that the endpoint is included
np.linspace(1, 100, num=33)

array([  1.     ,   4.09375,   7.1875 ,  10.28125,  13.375  ,  16.46875,
        19.5625 ,  22.65625,  25.75   ,  28.84375,  31.9375 ,  35.03125,
        38.125  ,  41.21875,  44.3125 ,  47.40625,  50.5    ,  53.59375,
        56.6875 ,  59.78125,  62.875  ,  65.96875,  69.0625 ,  72.15625,
        75.25   ,  78.34375,  81.4375 ,  84.53125,  87.625  ,  90.71875,
        93.8125 ,  96.90625, 100.     ])

In [5]:
# Not allowing the enpoint drastically changes the values
np.linspace(1, 100, num=33, endpoint=False)

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25., 28., 31., 34., 37.,
       40., 43., 46., 49., 52., 55., 58., 61., 64., 67., 70., 73., 76.,
       79., 82., 85., 88., 91., 94., 97.])

In [6]:
np.logspace(1, 100, num=33, endpoint=False)

array([1.e+01, 1.e+04, 1.e+07, 1.e+10, 1.e+13, 1.e+16, 1.e+19, 1.e+22,
       1.e+25, 1.e+28, 1.e+31, 1.e+34, 1.e+37, 1.e+40, 1.e+43, 1.e+46,
       1.e+49, 1.e+52, 1.e+55, 1.e+58, 1.e+61, 1.e+64, 1.e+67, 1.e+70,
       1.e+73, 1.e+76, 1.e+79, 1.e+82, 1.e+85, 1.e+88, 1.e+91, 1.e+94,
       1.e+97])

In [7]:
x=np.array([1,2,3,4])
y=np.array([1,2,3,4])
np.meshgrid(x,y)

[array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])]