# Python Plotting With Matplotlib

By the end of this course, you’ll:

    Know the differences between PyLab and Pyplot
    Grasp the key concepts in the design of matplotlib
    Understand plt.subplots()
    Visualize arrays with matplotlib
    Plot by combining pandas and matplotlib


## Video 1: Overview

Plotting library. It's a massive library, but the beginnings are pretty simple to get started with. This course will cover the foundations.

## Video 2: NumPy Review

NumPy - Numerical Python - is required for Matplotlib. Provides efficient mathematical operations for manipulating data

In [1]:
import numpy as np

#### numpy.random.seed()
sets the seed for the pseudorandom process. Setting the seed ensures programs using random numbers generate the same outcome

Python uses ndarrays. Like a python list but with a fixed size and common data type. 

#### numpy.arange()

creates a one-dimensional ndarray filled with evenly spaced values. Lower bound is inclusive; upper bound is excluded.

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(start=1, stop=6, step=2)

array([1, 3, 5])

In [5]:
# notice 5 is not included
np.arange(start=1, stop=5, step=2)

array([1, 3])

In [6]:
np.arange(start=.5, stop = 5, step = .5)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

#### numpy.random.randint()

Generates numbers between a lower bound(inclusive) and an upper bound (exclusive). The size parameter dictates the shape of the ndarray. 

In [8]:
# this will return a two-dimensional array consisting of 3 arrays of 4 elements each
np.random.randint(low=0, high=10, size=(3,4))

array([[5, 2, 1, 0],
       [3, 1, 4, 2],
       [0, 8, 1, 6]])

####  numpy.column_stack()

Stacks two one-dimensional ndarrays on top of each other

In [9]:
a = np.arange(1, 4)
b = np.arange(4, 7)

## each array becomes a column
.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
(a, b)

(array([1, 2, 3]), array([4, 5, 6]))

In [11]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

#### Transposing and Reshaping

reshape() can change the dimensions of an array. Transpose will switch the rows and columns

In [13]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [14]:
b = x.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
c = x.reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
# total number of elements needs to match
d = x.reshape(4,5)
d

ValueError: cannot reshape array of size 6 into shape (4,5)

In [23]:
c.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

#### numpy.diag()

creates a two dimensional array out of the numbers we supply are on the main diagonal and the rest of the entries are 0.

In [26]:
a = np.linspace(start = 0, stop = 4, num = 5)
np.diag(a)

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])